apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_CONTAINER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $CI_CONTAINER_NAME
  template:
    metadata:
      labels:
        app: $CI_CONTAINER_NAME
    spec:
      containers:
        - name: $CI_CONTAINER_NAME
          image: $CI_APPLICATION_REPOSITORY
          ports:
            - containerPort: 3500
      imagePullSecrets:
        - name: $secret_name
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_CONTAINER_NAME
spec:
  type: NodePort
  ports:
    - port: 3500
      targetPort: 3500
  selector:
    app: $CI_CONTAINER_NAME
---